export enum SupportedItemTypes {
  Laptop = 'Laptop',
  // Desktop = 'Desktop',
  Tablet = 'Tablet',
  Phone = 'Phone',
  Keyboard = 'Keyboard',
  Webcam = 'Webcam',
  Mouse = 'Mouse',
  Monitor = 'Monitor',
  Speakers = 'Speakers',
  Headphones = 'Headphones',
  Microphone = 'Microphone',
  // Chair = 'Chair',
  // Desk = 'Desk',
  Ide = 'Ide',
  Terminal = 'Terminal',
  // IdeTheme = 'IdeTheme',
  // IdePlugin = 'IdePlugin',
  Browser = 'Browser',
}
