export enum SupportedItemTypes {
  Laptop = 'Laptop',
  Desktop = 'Desktop',
  Tablet = 'Tablet',
  Phone = 'Phone',
  Keyboard = 'Keyboard',
  Mouse = 'Mouse',
  Monitor = 'Monitor',
  Speaker = 'Speaker',
  Headphone = 'Headphone',
  Microphone = 'Microphone',
  Chair = 'Chair',
  Desk = 'Desk',
  Ide = 'Ide',
  IdeTheme = 'IdeTheme',
  IdePlugin = 'IdePlugin',
  Browser = 'Browser',
}
